### ISSUE TITLE
title

### ISSUE THREAD

**Issue by franfranfranfran** [Antons92/prj-rev-bwfs-dasmoto#1]
https://github.com/Antons92/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L4

woops, dont forget to fill in the title! this info is very prominently displayed on the tab of the browser you open the page with, so it is pretty crucial

**Comment by Antons92** [comment]
ah, thanks. i checked the code before i uploaded it. But i didn't notice that i forgot the title :(
A mistake happens very fast. thanks for reviewing
