### ISSUE TITLE
local images

### ISSUE THREAD

**Issue by franfranfranfran** [Antons92/prj-rev-bwfs-dasmoto#3]
https://github.com/Antons92/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L11
https://github.com/Antons92/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L9
etc...

it is very important for your resources to be included in your project. links to outside sources can easily become broken if that source decides to change where they are stored or take them down. save your images locally to an 'images' folder inside of resources and then link to them using relative file paths.
the link to css on line 5 of your html is a great example and more info about relative file paths can be found [here](http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/)

**Comment by Antons92** [comment]
fixed in both files.  the link in the css file didn't work after fixing. but then i realize i the css file was in another directory so i had to change the link from  ./resources/images/pattern.jpeg into  ../images/pattern.jpeg. learned a lot so far!
